# for "locally running" this app in isolation

services:
  booknlp:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - /mnt/wato-drive2/j257jian/repos/booknlp/examples:/app/examples
    command: /bin/bash
